### ISSUE TITLE
Instructions on usage

### ISSUE THREAD

**Issue by pertrai1** [alixander/Ceruleum#2]
I have downloaded but I see a regular app directory structure. What are the instructions on how to get this running in the background? Can you add instructions in README?

**Comment by alixander** [comment]
Hey, thanks for checking it out! Sorry the README isn't so clear. Once you open the app up, just select the directory you want to keep track of. There are a few considerations
1. The directory must version controlled with git.
2. The files you want to track are first `git add`ed. So for example, to track all files from a brand new directory, you'd run `git init` followed by `git add --all` and then selecting the directory should bring up the files with changes tracked.

Here's a gif

![usage](https://user-images.githubusercontent.com/3120367/29388677-969fff56-82d5-11e7-8865-23d9f6fbf002.gif)
